[phases.setup]
nixPkgs = ['nodejs_20', 'yarn']

[variables]
NODE_VERSION = "20"
YARN_VERSION = "1.22.22"

[phases.build]
cmds = [
  "yarn install",
  "yarn build"
]

[phases.start]
cmd = "yarn start"
