[phases.setup]
nixPkgs = ['nodejs_20', 'yarn']

[variables]
NODE_VERSION = "20"

[phases.build]
cmds = [
  "nix-shell -p nodejs_20 --run 'yarn install'",
  "nix-shell -p nodejs_20 --run 'yarn build'"
]

[phases.start]
cmd = "nix-shell -p nodejs_20 --run 'yarn start'"
