[phases.setup]
nixPkgs = ['nodejs_22', 'yarn']

[variables]
NODE_VERSION = "22.11.0"
YARN_VERSION = "1.22.22"

[phases.build]
cmds = [
  "nix-shell -p nodejs_22 --run 'yarn install'",
  "nix-shell -p nodejs_22 --run 'yarn build'"
]

[phases.start]
cmd = "nix-shell -p nodejs_22 --run 'yarn start'"
